"""initial schema

Revision ID: 1d3275fda36f
Revises: 
Create Date: 2026-08-06 22:01:21.021485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d3275fda36f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.CheckConstraint('name = lower(name)', name=op.f('ck_tags_name_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("url LIKE 'http://%' OR url LIKE 'https://%'", name=op.f('ck_bookmarks_url_scheme')),
    sa.CheckConstraint('length(trim(title)) > 0', name=op.f('ck_bookmarks_title_not_blank')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookmarks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookmarks'))
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index('ix_bookmarks_user_id_created_at', ['user_id', 'created_at'], unique=False)

    op.create_table('bookmark_tags',
    sa.Column('bookmark_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookmark_id'], ['bookmarks.id'], name=op.f('fk_bookmark_tags_bookmark_id_bookmarks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_bookmark_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bookmark_id', 'tag_id', name=op.f('pk_bookmark_tags'))
    )
    with op.batch_alter_table('bookmark_tags', schema=None) as batch_op:
        batch_op.create_index('ix_bookmark_tags_tag_id', ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_bookmark_tags_tag_id')

    op.drop_table('bookmark_tags')
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index('ix_bookmarks_user_id_created_at')

    op.drop_table('bookmarks')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
